### ISSUE TITLE
Is it possible to use RunVelocity partially, in an integrated dataset?

### ISSUE THREAD

**Issue by davisidarta** [satijalab/seurat-wrappers#1]
Hi there Seurat team!

I'm sorry if this is the wrong place to post this question - please let me know. I'm merging several Seurat objects with FindIntegrationAnchors and IntegrateData. 

One of these objects came from a .loom velocyto output, and I wonder if I'll be able to run RunVelocity and plot the RNA velocity only for the cells belonging to that original dataset, even on a merged-dataset embedding. 

Do you have any recommendations on how to proceed?

**Comment by mojaveazure** [comment]
Hi @davisidarta,

There currently isn't support in `RunVelocity` to use only a subset of the cells. We suggest that after integration, then subset the integrated object back to the original cells that velocity was calculated for

```R
subset.object <- integrated.object[, colnames(velocyto.object)]
```

**Comment by kvshams** [comment]
Similar question, Is it possible to use `RunALRA(object, split.by="Treatment")` to have ALRA reduce the treatment bias?
