### ISSUE TITLE
cannot install seuratwrappers 

### ISSUE THREAD

**Issue by Ahmed-fub** [satijalab/seurat-wrappers#100]
when I use this 
`remotes::install_github('satijalab/seurat-wrappers)`

it gave me error 
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'R.utils'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'SeuratWrappers'
* removing 'C:/Users/Ahmed/Documents/R/win-library/4.1/SeuratWrappers'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Ahmed/AppData/Local/Temp/RtmpcLT5cX/file2ee471381aa3/SeuratWrappers_0.3.0.tar.gz’ had non-zero exit status

I have 
seurat4.
R 4.1.0

**Comment by andrewwbutler** [comment]
Hi,

Are you able to install `R.utils` ? 

```R
install.packages("R.utils")
```

**Comment by lstankiewicz15** [comment]
I get the same error. Is there any work arounds for PCs?

**Comment by andrewwbutler** [comment]
This looks like a github API timeout. You can wait until your limit resets and try again or add the PAT as suggested in the message.

**Comment by Ahmed-fub** [comment]
I reinstalled r and installed it through conda well without errors

**Comment by qrzhang** [comment]
Guys, please check this link! It saves my day.

#https://gist.github.com/z3tt/3dab3535007acf108391649766409421

To make it simple:
1. run in R `usethis::create_github_token()`
2. On pop-up website, generate and copy your own taken
3. run in R, `credentials::set_github_pat("YourPATinStep2")`
4. Verify setting in R, `usethis::git_sitrep()`
5. Run this in R, `remotes::install_github('satijalab/seurat-wrappers')`
