### ISSUE TITLE
as.cell_data_set don't work

### ISSUE THREAD

**Issue by l-magnificence** [satijalab/seurat-wrappers#106]
Please try updating to Seurat v4.0.3 and see if that resolved the issue.

_Originally posted by @andrewwbutler in https://github.com/satijalab/seurat-wrappers/issues/96#issuecomment-863541318_

when I run the function in seurat v4.0.3, it doesn't work
```
cds <- as.cell_data_set(seurat_obj) or  cds <- as.cell_data_set(seurat_obj,assay="SCT")
Error in method(object) : all assays must have the same nrow and ncol
```

**Comment by andrewwbutler** [comment]
Hi,

Turns out this was a different problem. I believe we've fixed both now on the `develop` branch. Please see installation instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1) and see if that resolves the issue.
