### ISSUE TITLE
I can not install [SeuratWrappers] successfully-As below

### ISSUE THREAD

**Issue by guilingma** [satijalab/seurat-wrappers#123]
[remotes::install_github('satijalab/seurat-wrappers')]

After I do this in my Rstudio:
The following appears, and I do not know how to install the package. I am with windows
Thank you very much

[**Error:** Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 69.166.47.172. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2022-03-04 17:30:35 UTC

  To increase your GitHub API rate limit
  - Use `usethis::create_github_token()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.]

**Comment by timoast** [comment]
I think in this case the error message already tells you how to resolve the issue

**Comment by guilingma** [comment]
Hi seurat-wrappers developers,

Thank you very much.

Now, the issue is solved.

Have a great weekend.
________________________________
