### ISSUE TITLE
Using Custom reductions with velocity in SeuratWrappers

### ISSUE THREAD

**Issue by SUN-Changyu** [satijalab/seurat-wrappers#13]
Hi, I am using SeuratWrappers to run RNA velocity with Seurat. The result is great, but I want to plot the graph with my own UMAP projections. I've tried assigning the projections directly to the embedding and CreateDimReducObject() to do the job, but nothing worked. Is there a way to use custom reduction in this situation?

**Comment by mojaveazure** [comment]
Hi Changyu,

I'm confused about what you're trying to accomplish. For `RunVelocity`, you can specify a reduction to use with the `reduction` parameter for calculating the embedding distance matrix (see the docs for `RunVelocity`). We do not provide a wrapper for visualization. Instead, we use velocyto.R's `show.velocity.on.embedding.cor` function, for which you can simply pass the embeddings matrix of a dimensional reduction to use for visualization (see our [vignette](https://github.com/satijalab/seurat-wrappers/blob/master/docs/velocity.md) for more details).

**Comment by SUN-Changyu** [comment]
Hi, Paul,
I've already figured out how to do it! Thanks so much for the quick response. 
What I wanted to do is to add a UMAP projections I generated earlier using Seurat to the Seurat object converted by SeuratWrappers from loom file. And to do so, I need to rename the column and row names of the embedding matrix and use CreateDimReducObject() to create a new reduction for the Seurat object. Problem solved. Thanks!

**Comment by CodeInTheSkies** [comment]
Hi @SUN-Changyu ,

This is the exact problem I am facing now, and would appreciate some more clarification as to how you went about finding a solution!

So, if I do this first from the loom file,
` ldat <- ReadVelocity(file="a.loom")`
`bm <- as.Seurat(x = ldat)`

then my `bm` object would have three assays, namely, "spliced" "unspliced" and "ambiguous".

Now, if I have another Seurat V2 object, which has the TSNE embeddings from earlier, then I first do

`new_pbmc=UpdateSeuratObject(object = pbmc)`

I also then do some steps to make sure the cell names for both `bm` and `new_pbmc` exactly match.

Can you please let me know what exactly is needed after this step to plot velocity projections onto the old TSNE embeddings?

Thanks a lot for your response!

**Comment by SUN-Changyu** [comment]
Hi, @CodeInTheSkies ,
I managed to use my own UMAP projection in SeuratWrapper by using the function CreateDimReducObject(). You would need to set a matrix to store your projection and then assign it to the seurat object in use.
Here is what I did to project the UMAP coordinates and this should be down before you run velocity.
`load("SAMPLE_UMAP.Robj")
numap <- as.matrix(umap.data[,1:2])
rownames(numap) <- rownames(bm@reductions[["umap"]]@cell.embeddings[,1:2])
colnames(numap) <- paste0("UMAP_", 1:2)
bm@reductions[["numap"]] <- CreateDimReducObject(embeddings = numap, key = "UMAP_", assay = DefaultAssay(bm))`

**Comment by CodeInTheSkies** [comment]
Thank you very much, @SUN-Changyu , for your response, and the code.  Appreciate it!

Just for your information, and also for any others who may be having the same question, I found this thread [  https://github.com/satijalab/seurat-wrappers/issues/9 ] and ended up using the suggestion therein, to manually add the "spliced", "unspliced", and the "ambiguous" assays one by one to my existing Seurat object containing my pre-calculated tSNE embeddings.  After that, simply following the rest of the steps did the trick in my case to draw velocity arrows on my existing tSNE.

Particular reference to @mojaveazure 's and @CoderMatthias 's suggestions in the above thread.

Special kudos to the `SeuratWrappers` team!!!  Thanks to their efforts integrating RNA velocity into the Seurat framework, it has become much easier to run RNA velocity.  Before that, it was a struggle, _at least for me!_

**Comment by sikh09** [comment]
Hi, I run the velocyto using Seurat successfully on my dropest martices.  Now,  I found there are many doublets in my single-cell data. I want to filter these cells and again run the velocyto to avoid the noise. 
Initially I have dropest matrices with 4000 cells and I want to filter 2000 cells.
