### ISSUE TITLE
Error：undefined exports: [batchelor]{fastMNN}

### ISSUE THREAD

**Issue by ShengFang-0829** [satijalab/seurat-wrappers#152]
remotes::install_github("satijalab/seurat-wrappers", "seurat5") 

log：
Error: package or namespace load failed for ‘SeuratWrappers’ in namespaceExport(ns, exports):
 undefined exports: [batchelor]{fastMNN}
Error: loading failed
Execution halted
ERROR: loading failed

Namespace maybe wrong？

**Comment by dbrookeUAB** [comment]
I found the problem.  `[batchelor]{fastMnn}` was misplaced from the `@note`.

```r
#'
#' @importFrom Seurat DefaultAssay DefaultAssay<- SelectIntegrationFeatures VariableFeatures VariableFeatures<-
#' as.SingleCellExperiment CreateDimReducObject Tool<- LogSeuratCommand
#' @importFrom rlang check_installed
#'
#' @export
#'[batchelor]{fastMNN}
#'@note This function requires the
#' \href{https://rdrr.io/github/LTLA/batchelor/}{\pkg{batchelor}} package
#' to be installed
#'
```

In the meantime, this works
- download the repo ([zip file link](https://github.com/satijalab/seurat-wrappers/archive/refs/heads/seurat5.zip))
- open the project in RStudio (`seurat-wrappers.Rproj`) 
- open the `NAMESPACE` file and remove the line `export("[batchelor]{fastMNN}")` ➔ Save. 
- open the Build Tab ➔ Install (Clean and Install)

**Comment by yuanlizhanshi** [comment]
Hello, I recently noticed this problem and successfully fixed it.

I think the problem @dbrookeUAB issued is right, but we can't remove `export("[batchelor]{fastMNN}")` 

Here is my solution:

1. Download the whole project and unzip
2. Clik `seurat-wrappers.Rproj` and opened with Rstudio
3. Replaced the `export("[batchelor]{fastMNN}")`  to ` importFrom(bachelor, "fastMNN")` in the `NAMESPACE ` file

Then  install the package (title panel：Bulid/install package or Ctrl + Shift +B)

Will be successful installed!

**Comment by Wang-Cankun** [comment]
I have created a PR https://github.com/satijalab/seurat-wrappers/pull/156 using the solutions by @yuanlizhanshi and @inofechm

Meanwhile, if you don't want to manually update the NAMESPACE file while the PR is pending, you can install the forked version from my GitHub repository:
```
remotes::install_github("Wang-Cankun/seurat-wrappers", "seurat5", quiet = F)
```

**Comment by yuanlizhanshi** [comment]
> Just a heads up, theres a typo in the above response `importFrom(bachelor, "fastMNN")` should be `importFrom(batchelor, "fastMNN")`

fixed it, thank you

**Comment by jogiles** [comment]
> I have created a PR #156 using the solutions by @yuanlizhanshi and @inofechm
> 
> Meanwhile, if you don't want to manually update the NAMESPACE file while the PR is pending, you can install the forked version from my GitHub repository:
> 
> ```
> remotes::install_github("Wang-Cankun/seurat-wrappers", "seurat5", quiet = F)
> ```

I had the same issue and this worked for me! Thank you.

**Comment by mbatiuk** [comment]
> Just a heads up, theres a typo in the above response `importFrom(bachelor, "fastMNN")` should be `importFrom(batchelor, "fastMNN")`

Gives an error:

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘batchelor’

**Comment by Gesmira** [comment]
[PR fixing this](https://github.com/satijalab/seurat-wrappers/pull/157) has been merged now. Thanks all for the details and catching the fix!
The updated package can be installed with: 
`remotes::install_github("satijalab/seurat-wrappers", "seurat5", quiet = TRUE)`
