### ISSUE TITLE
scVI defaults

### ISSUE THREAD

**Issue by adamgayoso** [satijalab/seurat-wrappers#154]
It's great to see scVI in Seurat!

Just a few quick things about how I'd set the defaults

I would use `gene_likelihood="nb", n_latent=30, n_layers=2` in order to match what is used in various benchmarks (e.g., scIB) and our tutorials

https://github.com/satijalab/seurat-wrappers/blob/0bc0fec2dce6d233a33da572bc2d877be84f4341/R/scVI.R#L66-L68

I would also use a default of `None` epochs

https://github.com/satijalab/seurat-wrappers/blob/0bc0fec2dce6d233a33da572bc2d877be84f4341/R/scVI.R#L53

as this uses our heuristic based on the data size.

**Comment by yuhanH** [comment]
Hi, Adam

Thank you for your suggestions. I have changed the default settings and will update our vignettes results soon.
