### ISSUE TITLE
Failed to install Seurat-Wrappers

### ISSUE THREAD

**Issue by Akanagooori** [satijalab/seurat-wrappers#155]
I ran into this error when using remote to install Seurat-Wrappers. I wish if anyone would help me with this problem. Thanks a lot.

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘R.utils’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘SeuratWrappers’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/SeuratWrappers’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/6k/tvk1zqzj2v58_04yj5czk3th0000gn/T//Rtmp9x4KOU/file1346c68a0ce93/SeuratWrappers_0.3.1.tar.gz’ had non-zero exit status

**Comment by Wang-Cankun** [comment]
Just install R.utils and try again:
```
install.packages("R.utils")
```

**Comment by Akanagooori** [comment]
> and

Problem solved！Thank you very much！
