### ISSUE TITLE
Velocyto Estimation Embedding image quality

### ISSUE THREAD

**Issue by ZornLab** [satijalab/seurat-wrappers#16]
Dear Seurat Team,
Introducing RNA-velocyto workflow in seurat is very helpful. Can you please help us with image quality. showembeddings function saves .TIFF image but the quality is very poor. 

Any Suggestions ?

Cheers

**Comment by mojaveazure** [comment]
We use the visualization functions from [velocyto.R](https://github.com/velocyto-team/velocyto.R), not our own; I would suggest asking this issue there.
