### ISSUE TITLE
May I ask the author if there is a way for me to get wrappers that support seruat4?

### ISSUE THREAD

**Issue by xiongsircool** [satijalab/seurat-wrappers#171]
![image](https://github.com/satijalab/seurat-wrappers/assets/45034344/dddcd7bb-9cd9-4410-88bc-5c8891612e83)

Recently I need a seruat4 version of seurat-wrappers but it seems that this package is not supported now.

**Comment by genesis18603** [comment]
I'm also struggling with this issue.

**Comment by timoast** [comment]
```r
remotes::install_github("satijalab/seurat-wrappers@a59e9b25ec8f9081890fd38e1073c0dfc74bf8e1")
```

**Comment by xiongsircool** [comment]
> > ```r
> > remotes::install_github("satijalab/seurat-wrappers@a59e9b25ec8f9081890fd38e1073c0dfc74bf8e1")
> > ```
> 
> Thank you for your reply, but I have encountered a new problem. How did you solve this issue? ![image](https://user-images.githubusercontent.com/151613006/284536902-f75f4a7a-71cf-43a1-b99f-ad5588a66159.png)



you can down  the package url: https://codeload.github.com/satijalab/seurat-wrappers/legacy.tar.gz/cc29d3e9d4f6330c1a8923947a1f22cd1d05c3f6
then you install

**Comment by genesis18603** [comment]
> > > ```r
> > > remotes::install_github("satijalab/seurat-wrappers@a59e9b25ec8f9081890fd38e1073c0dfc74bf8e1")
> > > ```
> > 
> > 
> > Thank you for your reply, but I have encountered a new problem. How did you solve this issue? ![image](https://user-images.githubusercontent.com/151613006/284536902-f75f4a7a-71cf-43a1-b99f-ad5588a66159.png)
> 
> you can down the package url: https://codeload.github.com/satijalab/seurat-wrappers/legacy.tar.gz/cc29d3e9d4f6330c1a8923947a1f22cd1d05c3f6 then you install

Thank you very much for your help. You helped me resolve the problem smoothly! Thank you, thank you, thank you!!!!
