### ISSUE TITLE
How can I get the integrated assay after running RunFastMNN()?

### ISSUE THREAD

**Issue by qoiopipq** [satijalab/seurat-wrappers#18]
Hi,

I've used RunFastMNN() to integrate two batches following this link:
http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/fast_mnn.html
It works quite well.

Now I want to get the integrated assay to do a trajectory analysis. However, I've noticed that after running RunFastMNN(), there is only one active assay "RNA". 
I think I should use the integrated assay for a trajectory analysis. Is there a way to get the integrated assay and use it to do a trajectory analysis?

Thanks!

**Comment by qoiopipq** [comment]
Manged to get MNN dimensional reduced coordinates and put this matrix directly into downstream pseudotime inference analysis.

**Comment by mojaveazure** [comment]
Hi,

Sorry for the delay, but I believe you figured this out. `RunFastMNN` does not return an `Assay`, but instead a `DimReduc` object. We use this dimensional reduction object as the input for the nearest neighbors graph, which allows an integrated clustering.
