### ISSUE TITLE
past versions of seurat-wrappers that fits seurat v4

### ISSUE THREAD

**Issue by Jiayi-Zheng** [satijalab/seurat-wrappers#185]
Hello, I had a lot of problem installing seurat 5 so i ended up retorting to installing seurat 4. However, the new seurat-wrappers can only fit seurat 5. I couldn't find the log of released versions of seurat wrappers, is there a way I can retrieve it somewhere? 

Sorry if it's a very naive question, I'm not particularly familiar with my way in github

**Comment by liuxr2022** [comment]
Hi,Have you solved it? I  met the same problem.

**Comment by liym0758** [comment]
> Hi, try this: remotes::install_github('satijalab/seurat-wrappers@community-vignette', quiet = TRUE)

Thank you soooo much! I tried your solution and it works!

**Comment by lancelotzhang0124** [comment]
> Hi, try this: remotes::install_github('satijalab/seurat-wrappers@community-vignette', quiet = TRUE)

Thank you sooooo much!

**Comment by Jiayi-Zheng** [comment]
> Hi, try this: remotes::install_github('satijalab/seurat-wrappers@community-vignette', quiet = TRUE)

Thank you!
