### ISSUE TITLE
RunVelocity error (requested size too large)

### ISSUE THREAD

**Issue by carlosf79** [satijalab/seurat-wrappers#21]
I have successfully run the example in the vignette. However, when trying on my data, I get the following error at the RunVelocity step:

> myse <- RunVelocity(object = myse, deltaT = 1, kCells = 25, fit.quantile = 0.02)
Filtering genes in the spliced matrix
Filtering genes in the unspliced matrix
Calculating embedding distance matrix
error: Mat::init(): requested size is too large
Error in arma_mat_cor(mat) : Mat::init(): requested size is too large

The object has quite some cells, is there a way to be able to run the velocity analysis?

> dim(myse)
[1] 28397 85697

I am running this on a machine with 384 GB RAM.

Thank you very much for your help!

**Comment by mojaveazure** [comment]
That's interesting as a numeric matrix of those dimensions takes ~20Gb of memory. What else do you have in your session? You may have too many things in memory; try removing some and running `gc()` to clear out unused memory.

**Comment by khedro** [comment]
I have the same issue !! Help please
