### ISSUE TITLE
Velocyto using SeuratWrappers: Error in seq.default(rx[1], rx[2], length.out = grid.n) : 'from' must be a finite number

### ISSUE THREAD

**Issue by whelena** [satijalab/seurat-wrappers#22]
I got this error when running
show.velocity.on.embedding.cor(emb = Embeddings(object = endo_sub, reduction = "umap"),
vel = Tool(object = endo_sub, slot = "RunVelocity"), n = 200, scale = "sqrt", cell.colors = ac(x = cell.colors, alpha = 0.5),
cex = 0.8, arrow.scale = 3, show.grid.flow = TRUE, min.grid.cell.mass = 0.5, grid.n = 40, arrow.lwd = 1,
do.par = FALSE, cell.border.alpha = 0.1)

Error in seq.default(rx[1], rx[2], length.out = grid.n) :
'from' must be a finite number

I've read comments of NaN values but I'm not sure where to start checking

**Comment by mojaveazure** [comment]
This seems to be an issue with velocyto.R; I would suggest posting an issue on [their GitHub repository](https://github.com/velocyto-team/velocyto.R)
