### ISSUE TITLE
Subclustering after fastMNN batch correction

### ISSUE THREAD

**Issue by nicodemus88** [satijalab/seurat-wrappers#23]
Hi, 
I was wondering what would be the best approach to perform clustering on a subset of cells pulled out from a MNN-batch-corrected object. 
I used `fastMNN` from `SeuratWrappers` to perform a MNN batch-correction and perform an integrated analysis. 
Then I subsetted a cluster of cells and wanted to perform re-clustering. 
Should I proceed with a Seurat workflow (standard or SCT) or do I need to perform another round of MNN batch-correction?
Thank you.

**Comment by mojaveazure** [comment]
Hi,

This is a question for the [batchelor people](https://github.com/LTLA/batchelor) (developers of fastMNN). This package merely serves as an interface between these methods and Seurat; as such, we are unable to provide help for these methods themselves, simply technical support.
