### ISSUE TITLE
Running alra in integrated data

### ISSUE THREAD

**Issue by kvshams** [satijalab/seurat-wrappers#5]
Hi,
Thank you for the great functions for `Seurat` and making life more easy. Is it possible to run alra on integrated data by preserving the conditions, ie something like RunALRA(object, split.by="Treatment") ?

**Comment by mojaveazure** [comment]
Currently, `RunALRA` does not support a `split.by` argument. If this is a feature you'd like, I'd suggest bringing it up with the authors of `RunALRA`

**Comment by kvshams** [comment]
I have already enquired the same in `ALRA` Github [page](https://github.com/KlugerLab/ALRA/issues/5). The curator suggested to follow [this](https://vanandelinstitute.github.io/va_ecls/final_analysis.html) method but not sure how to do it on Seurat.

**Comment by mojaveazure** [comment]
We wouldn't recommend running ALRA on the integrated data. If you want to integrate on the imputed data, you can run ALRA on each initial object (or split a merged `Seurat` object with [`SplitObject`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.2/topics/SplitObject)), then integrate each component object.
