### ISSUE TITLE
Error running Monocle3

### ISSUE THREAD

**Issue by ashwinikumarkulkarni** [satijalab/seurat-wrappers#52]
Hello! I have an integrated Seurat object (R 3.5.1, Seurat_3.1.5) which I am trying to use with SeuratWrapper's Monocle3 trajectory analysis (R 3.6.1, Seurat_3.1.5). Following the [tutorial](https://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/monocle3.html), I get following error running `cluster_cells` command. I also tried updating Seurat object using `UpdateSeuratObject`, but keep getting the same error. I can always re-run integration pipeline but I want to use the UMAP coordinates & cluster ids from my existing integration results. Please suggest a solution. Thanks! 

`> cds <- as.cell_data_set(integrated)`
`Warning: Monocle 3 trajectories require cluster partitions, which Seurat does not calculate. Please run 'cluster_cells' on your cell_data_set object`
`> cds <- cluster_cells(cds)`
`Error: No dimensionality reduction for UMAP calculated. Please run reduce_dimensions with reduction_method = UMAP before running cluster_cells`

**Comment by bensong721** [comment]
Just wanted to say that I too am having this issue.

cds <- as.cell_data_set(ciona.integrated)
Warning message:
“Monocle 3 trajectories require cluster partitions, which Seurat does not calculate. Please run 'cluster_cells' on your cell_data_set object”

cds <- cluster_cells(cds)
Error: No dimensionality reduction for UMAP calculated. Please run reduce_dimension with reduction_method = UMAP before running cluster_cells

cds <- reduce_dimension(cds, reduction_method = "UMAP")
No preprocess_method specified, using preprocess_method = 'PCA'

cds <- preprocess_cds(cds, method = "PCA")
Error in names(sf) <- colnames(SingleCellExperiment::counts(cds)): attempt to set an attribute on NULL

Any help would be appreciated!

**Comment by ashuchawla** [comment]
Did you guys run the UMAP on Seurat object? It fixed the issue for me.

integrated <- RunUMAP(integrated, dims = 1:<num_of_PCs>, reduction.name = "UMAP")

**Comment by ashwinikumarkulkarni** [comment]
@ashuchawla Yes! RunUMAP was already run during Seurat Integration pipeline. I already have the UMAP plot. And I want to map Monocle's pseudotime onto same UMAP coordinates.. which is where the error is.

**Comment by mojaveazure** [comment]
One of the requirements of Monocle 3 is that the dimensional reduction names are all upper-case, while Seurat defaults to lower-case names (eg. "UMAP" vs "umap"). The converter does not yet take care of this, but we are working on it. In the meantime, you can either pass `reduction.name = "UMAP"` to `RunUMAP` (as seen in the [vignette](http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/monocle3.html)) or rename a previously calculated UMAP result in Seurat before converting to Monocle 3

```r
seurat.object[["UMAP"]] <- seurat.object[["umap"]]
# To save on memory, you can delete the original UMAP, but this is not necessary
seurat.object[["umap"]] <- NULL
```

**Comment by mojaveazure** [comment]
This issue should be resolved in the latest version of SeuratWrappers. Thanks for reporting!

**Comment by ashwinikumarkulkarni** [comment]
Thanks a lot @mojaveazure! I think this will work. I am trying now!
