### ISSUE TITLE
issues with cds object in monocle3

### ISSUE THREAD

**Issue by eLoffet** [satijalab/seurat-wrappers#54]
Hello,
I have been working with the vignette integrating monocle3 and Seurat, which works fine, but I run into errors when trying to run other functions of monocle3.
I get this error with the graph_test function:

> graph <- graph_test(cds, neighbor_graph="principal_graph", cores=4)
Error in names(sf) <- colnames(SingleCellExperiment::counts(cds)) : 
  attempt to set an attribute on NULL

I also cannot plot genes with the plot_cells function of monocle3 :

> genes <- c("ACTG2","ACTA2")
> plot_cells(cds, genes=genes, label_cell_groups=FALSE, show_trajectory_graph=FALSE)
Error in plot_cells(cds, genes = genes, label_cell_groups = FALSE, show_trajectory_graph = FALSE) : 
  None of the provided genes were found in the cds

The plot_cells function otherwise works fine with other arguments (partitions, metadata from seurat, pseudotime, etc). Finding gene names seems to be the issue

Do you have any suggestions ?
Thanks for your help !

**Comment by eLoffet** [comment]
So I couldn't correct these errors with the cds object created with seurat-wrapper, but I tried to create a cds with my seurat object without using seuratwrapper, initially with this code : 

```
> data <- GetAssayData(object = seuratobj, slot = "counts")
celldata <- as.data.frame(seuratobj@meta.data)
cds <- new_cell_data_set(data, cell_metadata = celldata)

> Warning message:
> In new_cell_data_set(data, cell_metadata = celldata) :
>   Warning: gene_metadata must contain a column verbatim named 'gene_short_name' for certain functions.

```
There's a warning message but the object is created anyway, and if I continue with monocle3's preprocessing and clustering workflow, I get the exact same errors with graph_test() and plot_cells() with this object.

However, these issues dissapear if I create the cds object with a gene_metadata data frame (which is just a data frame where the gene names are in the row names and duplicated in column 1, because the function asks that the rownames of genedata and data be the same and to have a 'gene_short_name' column. I'm not sure what else is supposed to be in this data frame ?)

```
> data <- GetAssayData(object = seuratobj, slot = "counts")
celldata <- as.data.frame(seuratobj@meta.data)
genedata <- as.data.frame(x = row.names(data), row.names = row.names(data))
colnames(genedata) <- "gene_short_name"
cds <- new_cell_data_set(data, cell_metadata = celldata, gene_metadata = genedata)

```
So far every function from the following monocle3 workflow works, so I think my original issue is with the as.cell_data_set() conversion. I don't know what I can do differently to not have these errors with seurat-wrapper.

**Comment by mojaveazure** [comment]
It seems as though Monocle 3 objects require a cell-level metadata entry called "Size_factor"; I'm not sure how this is generated, so I don't have the ability or know-how to build it into the Seurat &rarr; Monocle 3 converter. This conversion was designed for running pseudotime analysis in Monocle 3, so I didn't test every aspect of the object. Maybe someone from @cole-trapnell-lab can comment?

**Comment by laijen000** [comment]
Hello! Thank you for the seurat wrapper and tutorial for working with monocle3. I am having the same issue when trying to use graph_test to find genes that change expression as a function of pseudotime, and plot gene expressions after converting seurat v3 to a cds using the new wrapper. 

plot_cells(cds, genes=genes, label_cell_groups=FALSE)
Error in names(sf) <- colnames(SingleCellExperiment::counts(cds)) : 
  attempt to set an attribute on NULL

plot_genes_in_pseudotime(cds, color_cells_by='pseudotime', min_expr=0.5)
Error in names(sf) <- colnames(SingleCellExperiment::counts(cds)) : 
  attempt to set an attribute on NULL

**Comment by nicodemus88** [comment]
@eLoffet, @laijen000, hope you find this useful. 
I managed to solve this issue by adding the gene names manually to the CDS and calculate the size factor using Monocle3.

```
library(monocle3)
library(SeuratWrappers)
cds <- as.cell_data_set(so)
**## Calculate size factors using built-in function in monocle3**
cds <- estimate_size_factors(cds)
**## Add gene names into CDS**
cds@rowRanges@elementMetadata@listData[["gene_short_name"]] <- rownames(so[["RNA"]])

```
With this, I was able to run graph_test and plot genes with plot_cells.

**Comment by mojaveazure** [comment]
SeuratWrappers will now add the nCount metadata field as size factors when converting to a `cell_data_set` object. As @nicodemus88 said, you can also use `monocle3::estimate_size_factors` to add your own.

**Comment by Edward-Chen-123** [comment]
> @eLoffet, @laijen000, hope you find this useful.
> I managed to solve this issue by adding the gene names manually to the CDS and calculate the size factor using Monocle3.
> 
> ```
> library(monocle3)
> library(SeuratWrappers)
> cds <- as.cell_data_set(so)
> 
> ## Calculate size factors using built-in function in monocle3
> cds <- estimate_size_factors(cds)
> 
> ## Add gene names into CDS
> cds@rowRanges@elementMetadata@listData[["gene_short_name"]] <- rownames(so[["RNA"]])
> ```
> 
> With this, I was able to run `graph_test` and plot genes with `plot_cells`.
> 
> Cheers!

Hi nicodemus88,

I followed your suggestion but when I try to display genes with plot_cells I still get this error message:

Error: subscript is a logical vector with out-of-bounds TRUE values.

Any ideas of how this can be fixed? Thank you very much!

**Comment by coolmak32** [comment]
Thank you so much nicodemus88.

**Comment by Leonruniing** [comment]
> > @eLoffet, @laijen000, hope you find this useful.
> > I managed to solve this issue by adding the gene names manually to the CDS and calculate the size factor using Monocle3.
> > ```
> > library(monocle3)
> > library(SeuratWrappers)
> > cds <- as.cell_data_set(so)
> > 
> > ## Calculate size factors using built-in function in monocle3
> > cds <- estimate_size_factors(cds)
> > 
> > ## Add gene names into CDS
> > cds@rowRanges@elementMetadata@listData[["gene_short_name"]] <- rownames(so[["RNA"]])
> > ```
> > 
> > 
> > With this, I was able to run `graph_test` and plot genes with `plot_cells`.
> > Cheers!
> 
> Hi nicodemus88,
> 
> I followed your suggestion but when I try to display genes with plot_cells I still get this error message:
> 
> Error: subscript is a logical vector with out-of-bounds TRUE values.
> 
> Any ideas of how this can be fixed? Thank you very much!


> > @eLoffet, @laijen000, hope you find this useful.
> > I managed to solve this issue by adding the gene names manually to the CDS and calculate the size factor using Monocle3.
> > ```
> > library(monocle3)
> > library(SeuratWrappers)
> > cds <- as.cell_data_set(so)
> > 
> > ## Calculate size factors using built-in function in monocle3
> > cds <- estimate_size_factors(cds)
> > 
> > ## Add gene names into CDS
> > cds@rowRanges@elementMetadata@listData[["gene_short_name"]] <- rownames(so[["RNA"]])
> > ```
> > 
> > 
> > With this, I was able to run `graph_test` and plot genes with `plot_cells`.
> > Cheers!
> 
> Hi nicodemus88,
> 
> I followed your suggestion but when I try to display genes with plot_cells I still get this error message:
> 
> Error: subscript is a logical vector with out-of-bounds TRUE values.
> 
> Any ideas of how this can be fixed? Thank you very much!

Hi,

I also met similar problems. Would you please share how do you solve it?  Thanks

**Comment by Lix1993** [comment]
thanks @nicodemus88 

besides, using `rownames(so)` may be better, since `as.cell_data_set` seems using active.assay, which may not be 'RNA'

**Comment by MaraLlamas** [comment]
> > > @eLoffet, @laijen000, hope you find this useful.
> > > I managed to solve this issue by adding the gene names manually to the CDS and calculate the size factor using Monocle3.
> > > ```
> > > library(monocle3)
> > > library(SeuratWrappers)
> > > cds <- as.cell_data_set(so)
> > > 
> > > ## Calculate size factors using built-in function in monocle3
> > > cds <- estimate_size_factors(cds)
> > > 
> > > ## Add gene names into CDS
> > > cds@rowRanges@elementMetadata@listData[["gene_short_name"]] <- rownames(so[["RNA"]])
> > > ```
> > > 
> > > 
> > > With this, I was able to run `graph_test` and plot genes with `plot_cells`.
> > > Cheers!
> > 
> > 
> > Hi nicodemus88,
> > I followed your suggestion but when I try to display genes with plot_cells I still get this error message:
> > Error: subscript is a logical vector with out-of-bounds TRUE values.
> > Any ideas of how this can be fixed? Thank you very much!
> 
> > > @eLoffet, @laijen000, hope you find this useful.
> > > I managed to solve this issue by adding the gene names manually to the CDS and calculate the size factor using Monocle3.
> > > ```
> > > library(monocle3)
> > > library(SeuratWrappers)
> > > cds <- as.cell_data_set(so)
> > > 
> > > ## Calculate size factors using built-in function in monocle3
> > > cds <- estimate_size_factors(cds)
> > > 
> > > ## Add gene names into CDS
> > > cds@rowRanges@elementMetadata@listData[["gene_short_name"]] <- rownames(so[["RNA"]])
> > > ```
> > > 
> > > 
> > > With this, I was able to run `graph_test` and plot genes with `plot_cells`.
> > > Cheers!
> > 
> > 
> > Hi nicodemus88,
> > I followed your suggestion but when I try to display genes with plot_cells I still get this error message:
> > Error: subscript is a logical vector with out-of-bounds TRUE values.
> > Any ideas of how this can be fixed? Thank you very much!
> 
> Hi,
> 
> I also met similar problems. Would you please share how do you solve it? Thanks

I am having this issue too. If it has been answered somewhere else, could you share the link please?

**Comment by apal6** [comment]
Hi, 

I followed the above suggestions and got this error : 
`deg <- graph_test(cds, neighbor_graph = "principal_graph")
Error in (function (..., deparse.level = 1, make.row.names = TRUE, stringsAsFactors = FALSE,  : 
  invalid list argument: all variables should have the same length`

Any recommendation as to how to fix this?

Thank you.

**Comment by nolanoriger** [comment]
Hi all, I was having this issue again and tried the above solution using `estimate_size_factors` to no avail. After looking through the [monocle3 code](https://rdrr.io/github/cole-trapnell-lab/monocle3/src/R/utils.R), I think there's an issue with the `is_sparse_matrix` function in the `estimate_size_factors` call. 

Honestly I'm not savvy enough to figure out what the actual solution would be, but I was able to find a workaround which involves manually adding the size factor metadata to the CDS by using Seurat metadata applied to the formulas found in the `estimate_size_factors` code:

```
# For mean-geometric-mean-total estimate_size_factors method
colData(cds)$Size_Factor <- obj$nCount_RNA / exp(mean(log(obj$nCount_RNA)))

# For mean-geometric-mean-log-total estimate_size_factors method
colData(cds)$Size_Factor <- log(obj$nCount_RNA) / exp(mean(log(log(obj$nCount_RNA))))

# Still need to manually add gene names
cds@rowRanges@elementMetadata@listData[["gene_short_name"]] <- rownames(cds[["SCT"]])
```

After the manual addition of the size factor metadata, I was able to continue on with the monocle3 workflow. Hopefully this helps someone that was stuck like I was!

**Comment by sedatkacar56** [comment]
> ```
> cds@rowRanges@elementMetadata@listData[["gene_short_name"]] <- rownames(so[["RNA"]])
> ```

Thank you benjytan88!!!
