### ISSUE TITLE
Trajectory Root Cells

### ISSUE THREAD

**Issue by ashuchawla** [satijalab/seurat-wrappers#56]
Hi,

I am unable to understand what "AVP" means in the following code. I am guessing that this code is trying to find cells with a certain value as trajectory starting point cells.
```
max.avp <- which.max(unlist(FetchData(integrated.sub, "AVP")))
max.avp <- colnames(integrated.sub)[max.avp]
cds <- order_cells(cds, root_cells = max.avp)
```
 **Now,  If I want the starting point to be all cells from cluster number 2, would it be ok to run** 
```
cluster2.cells <- WhichCells(object = seurat_obj_name, idents = 2)
cds <- order_cells(cds, root_cells = cluster2.cells)
```

Thanks,

Ashu

**Comment by nicodemus88** [comment]
@ashuchawla The "AVP" refers to a gene. In the vignette's case, the root cell is designated as the cell which have the highest expression of "AVP" gene. 

Since you're specifying a whole cluster, your method is correct. 

Cheers!

**Comment by ashuchawla** [comment]
Thank you so much @nicodemus88 !
