### ISSUE TITLE
seurat RNA velocity

### ISSUE THREAD

**Issue by notimenocall** [satijalab/seurat-wrappers#6]
Hi,
Thanks for developing the great tools and continuing having new additions.
My question is how to properly implement RNA velocity to Seurat objects. Specifically, what reference should be use for mapping: cDNA/introns info are required for velocity but I think mapping to the whole transcriptome may be more accurate. In this case, can we generate velocity with a seurat object consisting the spliced/unspliced assays and then transfer the calculated velocity info to another seurat object generated by mapping to the transcriptome by matching the cell identities? If so, how to do it? If not, what could be a better strategy?
Thanks much!
Xiao

**Comment by mojaveazure** [comment]
This was asked and answered at https://github.com/satijalab/seurat/issues/1893#issuecomment-515599821

**Comment by ZornLab** [comment]
Hi Seurat Team,
Integration of RNA-Velocyto in Seurat is great and easy to use. One problem is that the resolution of image which shows velocyto embeddings is very poor. Is there a way to save a high resolution image of the same?
