### ISSUE TITLE
the screening criteria of Nucleosome_signal using 'Signac'

### ISSUE THREAD

**Issue by Ariel-TC** [satijalab/seurat-wrappers#68]
I'm using 'Signac' for scATAC-Seq data analysis and i wondered why we should filter nucleosome signal upper than four? I had look up many papers but i still have no idea for the reason. Or maybe it just match the fragments size distribution condition? Does that mean that I could change the standard number which suit my own data? 
Best,
Ariel.

![image](https://user-images.githubusercontent.com/65101587/93547180-00fa4100-f997-11ea-8ff7-16083ca517a2.png)

**Comment by timoast** [comment]
Please raise this issue in the Signac repository
