### ISSUE TITLE
Convert Signac/Seurat object to monocle3 cds

### ISSUE THREAD

**Issue by Aitor91** [satijalab/seurat-wrappers#80]
Hi,

I have finished analyzing the scATACseq data using Signac package. Currently, I am trying to perform now the pseudotime analysis following Signac vignette and also Monocle3's explanations. However, when I move the Seurat object to monocle cds object following Signac Vignette, I lose the cluster names and clustering information. How could avoid that? Can I add them later? Is there any vignette that explains how to do that?

Any help would be great. Thank you very much.

Aitor

**Comment by andrewwbutler** [comment]
Hi @Aitor91 ,

Sorry for the late response. Could you elaborate on what you mean by "lose the cluster names and clustering information"? These should be present in the cell metadata and accessible after conversion with `colData(object)`.
