### ISSUE TITLE
update CheckPackage(package = "MacoskoLab/liger", repository = "github") to CheckPackage(package = "rliger", repository = "github")

### ISSUE THREAD

**Issue by erikjskie** [satijalab/seurat-wrappers#84]
Hello,

looking forward to using this wrapper but it seems that it isn't able to recognize the rliger package is installed. I have it installed from 

devtools::install_github('welch-lab/liger')

and it works fine independent of the wrapper. the package name is installed as 'rliger' now I believe that's the only change that is needed

**Comment by liron27** [comment]
I have the same issue!

**Comment by edbels** [comment]
I have the same issue. Have you found a solution for this problem yet?

Thanks!

**Comment by ShanSabri** [comment]
There's a pull request that needs to be approved to fix this issue.

**Comment by andrewwbutler** [comment]
Closing as this should be addressed now as of merging #87
