### ISSUE TITLE
Return AUC values from Presto

### ISSUE THREAD

**Issue by samuel-marsh** [satijalab/seurat-wrappers#85]
Hi Seurat/Seurat-Wrappers team,

Love the support for presto package through Seurat wrappers.  In running it today though it appears that `RunPresto` and `RunPrestoAll` don't return the AUC metric that running presto natively does.  Wondering if these functions could be updated to return this column as well (or param to specify returning this column TRUE/FALSE)?

Thanks!
Sam

**Comment by samuel-marsh** [comment]
Hi,

Tagging Presto devs @ilyakorsunsky and @slowkow on this.  Not sure if you all were involved in development of this wrapper (apologies for tagging if not) but wondering if you might have thoughts on adding the AUC values to outputs of `RunPresto` and `RunPrestoAll`.

Thanks!
Sam

**Comment by slowkow** [comment]
@samuel-marsh Sorry, I was not involved in developing the code for seurat-wrappers.

It appears that @jaisonj708 added the wrapper to this repo, so maybe that person might comment on this issue?

https://github.com/satijalab/seurat-wrappers/commit/b3c91f5b0d383c7dee2aa7646fafa416b32344f5

**Comment by samuel-marsh** [comment]
Hi @slowkow no worries and thanks for the response!!

**Comment by jaisonj708** [comment]
Thanks @samuel-marsh for the feature request, I have made a pull request (https://github.com/satijalab/seurat-wrappers/pull/88) which is currently in the review process.

**Comment by samuel-marsh** [comment]
@jaisonj708 Awesome thanks so much!!

**Comment by andrewwbutler** [comment]
Hi all,

Sorry for the delay on this. The PR is merged now.

**Comment by samuel-marsh** [comment]
Fantastic thanks so much!!
