### ISSUE TITLE
Error in the as.cell_data_set() function 

### ISSUE THREAD

**Issue by aditisk** [satijalab/seurat-wrappers#91]
Hello,

I'm trying to use Monocle3 with my Seurat object but I get an error in the first step:

> cds <- as.cell_data_set(cd8)
Error in isVirtualExt(exti) : 
  trying to get slot "virtual" from an object of a basic class ("NULL") with no slots

Any suggestions on how to get past this error and proceed with the Monocle3 analysis ? Thanks.

**Comment by andrewwbutler** [comment]
Hi,

Can you post a reproducible example? It looks like your `cd8` object might be `NULL` instead of a Seurat object.
