### ISSUE TITLE
ExportToCellbrowser doesn't exist

### ISSUE THREAD

**Issue by BingbingYuan** [satijalab/seurat-wrappers#92]
I downloaded the SeuratWrappers_0.3.0, but ExportToCellbrowser doesn't exist. Which version of the SeuratWrappers was used in the below documentation?
https://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/cellbrowser.html
Thanks,

**Comment by timoast** [comment]
It exists: https://github.com/satijalab/seurat-wrappers/blob/master/NAMESPACE#L10

I'd suggest restarting R and confirming you have version 0.3.0 installed and loaded
