### ISSUE TITLE
liger fails: because dependencies have moved

### ISSUE THREAD

**Issue by Varix** [satijalab/seurat-wrappers#94]
the liger.r functions mostly all fail because MacoskoLab is no longer maintaining the package, its now being maintained by welch-lab...

because the wrapper specifically looks for `CheckPackage(package = 'MacoskoLab/liger', repository = 'github')` even if you install the current maintained version its going to throw a hissy fit , also since the new repo uses a different naming conventions, the hardcoded `liger:: `  commands also fail...

I have fixed this in a local version , how do I go about uploading the fix to the repo? I can create a branch and push for the admins to check but do I need any special permissions to push a new branch? 

wanted to ask for permission before just uploading code... I tested this error on Ubuntu 20.04.2 LTS & Windows 10 and got the issue the same times. When I googled for a solution around what I thought was the problem I didn't find a solution or work around (I assume most people already had MacoskoLab/liger downloaded from before or had bundled in a docker or something)...

if there is already a better solution... i wasted a little time... but the vignette and the examples here on this repo didnt work as run so figured if there was a work around already it would have been in the example code.

hope you are all having a great weekend!

**Comment by Varix** [comment]
Okay I just tried to push my patch to a new branch but `remote: Permission to satijalab/seurat-wrappers.git denied to Varix.` so clearly I need permission added. Could an admin approve me? I am more active in the Bioconductor world but I am a bioinformatician and tumor immunologist at UPenn.

**Comment by Varix** [comment]
okay I think I figured out how this is being maintained. I have forked the repo, uploaded my fix , and created a pull request...

Thanks!

**Comment by andrewwbutler** [comment]
Closing as this should be addressed now as of merging https://github.com/satijalab/seurat/pull/4532
